db:
  image: mysql
  volumes: 
   - ~/Projetos/Alura/app/database/:/var/lib/mysql/
  environment: 
    - MYSQL_ROOT_PASSWORD=teste123

blog-alura:
  image: wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=teste123 
  links: 
    - db:mysql
  ports:  
    - 80:80